package com.example.dynamodbdemo.music.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "MusicCollection")
public class MusicCollection {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String artist;

    @DynamoDBAttribute
    @DynamoDBRangeKey
    private String songTitle;

    @DynamoDBAttribute
    private String albumTitle;

    public String getArtist() {
        return artist;
    }

    public void setArtist(String artist) {
        this.artist = artist;
    }

    public String getSongTitle() {
        return songTitle;
    }

    public void setSongTitle(String songTitle) {
        this.songTitle = songTitle;
    }

    public String getAlbumTitle() {
        return albumTitle;
    }

    public void setAlbumTitle(String albumTitle) {
        this.albumTitle = albumTitle;
    }
}
